name: Deploy

on:
  push:
    branches:
      - gh-pages-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Install packages
        run: npm i

      - name: Build assets
        run: npm run build

      - name: Move assets to tmp
        run: cp -r build tmp

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false

      - name: Move all assets from tmp to root
        run: mv -rf tmp/* .

      - name: Commit
        run: git add .
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
      - run: git commit --amend --no-edit
      - run: git push origin gh-pages
